blank_issues_enabled: false
contact_links:
- name: '📚 Documentation Issue'
  about: If Something is missing in the project or official documentation.
  url: https://github.com/wso2/docs-apim/issues/new/choose
- name: '💬 Slack Channel'
  url: 'https://apim-slack.wso2.com/'
  about: |
    Chat with the community to get quick clarifications for your questions.
